ItemEvents.modifyTooltips(event => {
  event.add('minecraft:bone_block', 'Bones can be obtained from certain Spore creatures.')
  event.add('minecraft:bone', 'Bones can be obtained from certain Spore creatures.')
  event.add('tiab:time_in_a_bottle', '\u00a77Can be used on Mounds to make them generate more Biomass. It however does not affect the mob spawning rate.')
  event.add('spore:scent_spawnegg', '\u00a77Summon Spore creatures for a period of time. The more space the better. Will only summon creatures if there is a target nearby. Can be Overcharged with Lava to summon stronger creatures under any condition.')
  event.add('create_netherless:coal_rod', '\u00a77Requires a blasting furnace to be converted into a Blaze Rod.')
  event.add('spore:container', '\u00a77Food can safely be stored in a B.C.U. without risking to be contaminated by a Mound.')
  event.add('spore:cdu', '\u00a77Purifies the area in a 8 blocks radius. Kills Spore creatures and purifies blocks!')
  event.add('spore:tumor', '\u00a77Throwable projectile.')
  event.add('spore:sicken_tumor', '\u00a77Throwable projectile.')
  event.add('spore:calcified_tumor', '\u00a77Throwable projectile.')
  event.add('spore:bile_tumor', '\u00a77Throwable projectile.')
  event.add('spore:frozen_tumor', '\u00a77Throwable projectile.')
  event.add('spore:brain_remnants', '\u00a77Obtained by killing a Proto Hivemind or destroying an Outpost Watcher.')
  event.add('spore:alveolic_sack', '\u00a77Right click a Cow with this item to milk it.')
  event.add('spore:biomass', '\u00a77You can eat this!')
  event.add('spore:biomass', '\u00a77Maybe you could automate this resource at some point?')
  event.add('create:zinc_nugget', '\u00a77Maybe you could automate this resource at some point?')
  event.add('create:copper_nugget', '\u00a77Maybe you could automate this resource at some point?')
  event.add('minecraft:iron_nugget', '\u00a77Maybe you could automate this resource at some point?')
  event.add('minecraft:iron_nugget', '\u00a77... Yeah you get it at this point: you could consider automating most things in this pack, if you feel like it :p')
  event.add('spore:organoid_membrane', '\u00a77Yeah, you could even automate this. Only if you feel up for the challenge of course, hehe')
})